# This is a basic workflow to help you get started with Actions

name: Automatic Interpolation v6

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  interpolate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      # NODE
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: install node packages
        run: npm install

      - name: get data
        run: node js/fetchData
        env:
          API_KEY: ${{secrets.AQ_API_KEY}}

      # PYTHON
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.x

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r py/requirements.txt
         
      - name: summarize data
        run: python py/summarize.py

      # R
      - name: Set up R 4.3
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.3

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache: false
          extra-packages: tidyverse, readr, phylin, sf
          needs: website, coverage

      - name: Interpolate Data
        run: Rscript Interpolation/InterpolateReadings.R
      
      - name: postprocess data
        run: python py/post.py
        
      # UPLOAD AND COMMIT
      - name: execute s3 push
        run: python py/upload.py
        env:
          S3_DEPLOYER_ID: ${{ secrets.S3_DEPLOYER_ID }}
          S3_DEPLOYER_KEY: ${{ secrets.S3_DEPLOYER_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
